#!/bin/bash

###1. Annotation using SwissProt
## Download Swissprot database
wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
unzip uniprot_sprot.fasta.gz

## Build DIAMOND database
diamond makedb --in uniprot_sprot.fasta --db swissprot.dmnd

## Align DNA query sequences against a protein reference database
diamond blastx \
    -d swissprot.dmnd \
    -q cluster_transcripts_fpkm0.5_s3.fa \
    -o sand_smelt_vs_swissprot.xml \
    --threads 20 \
    --max-target-seqs 5 \
    --ultra-sensitive \
    --evalue 1e-5 \
    --outfmt 5

###2. Extract unannotated sequence (Use "blastxml2tab" in this git)
## Filter annotated sequences
wget https://github.com/ISUgenomics/common_scripts/archive/refs/heads/master.zip
unzip master.zip
python2 /home/jade/common_scripts-master/blastXML2Tab.py \
    -o sand_smelt_vs_swissprot.m8 \
    -c std \
    sand_smelt_vs_swissprot.xml

cut -f1 sand_smelt_vs_swissprot.m8 | sort -u > annotated_ids_sws.txt
seqkit grep -v -f annotated_ids_sws.txt cluster_transcripts_fpkm0.5_s3.fa > unannotated_1.fa

##3. Annotate the rest but using TrEMBL
wget https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.fasta.gz
gunzip uniprot_trembl.fasta.gz

## Build DIAMOND database
diamond makedb --in uniprot_trembl.fasta --db trembl --threads 20

## Align DNA query sequences against a protein reference database
/home/jade/diamond blastx \
    -d trembl.dmnd \
    -q unannotated_1.fa \
    -o sand_smelt_vs_trembl.xml \
    --threads 20 \
    --max-target-seqs 5 \
    --ultra-sensitive \
    --evalue 1e-5 \
    --outfmt 5

## Integrate all annotated sequence, 30509 of 48384 contigs have been annotated
cat sand_smelt_vs_swissprot.xml sand_smelt_vs_trembl.xml > sand_smelt_annoation.xml

###4. Extract unannotated sequence (Use "blastxml2tab" in this git)
## Filter annotated sequences
python2 /home/jade/common_scripts-master/blastXML2Tab.py \
    -o sand_smelt_vs_sws_tre.m8 \
    -c std \
    sand_smelt_annoation.xml

cut -f1 sand_smelt_vs_sws_tre.m8 | sort -u > annotated_ids_sws_tre.txt
seqkit grep -v -f annotated_ids_sws_tre.txt cluster_transcripts_fpkm0.5_s3.fa > unannotated_2.fa

##5. Annotate the rest but using uniRef90
wget https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz
gunzip uniref90.fasta.gz

## Build DIAMOND database
/home/jade/diamond makedb --in uniref90.fasta.gz --db uniref90 --threads 20

## Align DNA query sequences against a protein reference database
/home/jade/diamond blastx \
    -d uniref90.dmnd \
    -q unannotated_2.fa \
    -o sand_smelt_vs_uniref90.xml \
    --threads 20 \
    --max-target-seqs 5 \
    --ultra-sensitive \
    --evalue 1e-5 \
    --outfmt 5

## Integrate all annotated sequence, 30509 of 48384 contigs have been annotated
cat sand_smelt_annoation.xml sand_smelt_vs_uniref90.xml > sand_smelt_annoation_all.xml
