#!/bin/bash

###Check contigs###
grep -o ">" <filename.fa> | wc -l

###‘TrinityStats.pl’ from Trinity accessory scripts: basic stats###
##https://github.com/trinityrnaseq/trinityrnaseq/tree/master/util##
##perl <TrinityStats.pl's path> [transcriptome]###
perl /home/jade/3_trinityrnaseq-v2.15.1/util/TrinityStats.pl transcripts_fpkm_0.fa

###Stats.sh from bbmap: basic stats###
/home/jade/anaconda3/bin/stats.sh in=transcripts.fa

###BUSCO: check biological meanings###


###Bowtie2: check mapping rate###
