#!/bin/bash

###Check contigs###
grep -o ">" <filename.fa> | wc -l

###‘TrinityStats.pl’ from Trinity accessory scripts: basic stats###
##https://github.com/trinityrnaseq/trinityrnaseq/tree/master/util##
##perl <TrinityStats.pl's path> [transcriptome]###
perl /home/jade/3_trinityrnaseq-v2.15.1/util/TrinityStats.pl transcripts_fpkm_0.fa

###Stats.sh from bbmap: basic stats###
/home/jade/anaconda3/bin/stats.sh in=transcripts.fa

###BUSCO: check biological meanings###


### Bowtie2: check mapping rate###
## Build ###
# Base directory for Bowtie2 indexes
INDEX_BASE=/home/jade/1_sandsmelt/rundrap/bowtie2_indexes

# Transcriptome FASTA files
TRANS1=~/1_sandsmelt/rundrap/out_drap/meta_BR/d-cov_filter/transcripts_fpkm_1.fa
TRANS3=~/1_sandsmelt/rundrap/out_drap/meta_BR/d-cov_filter/transcripts_fpkm_3.fa
TRANS5=~/1_sandsmelt/rundrap/out_drap/meta_BR/d-cov_filter/transcripts_fpkm_5.fa

# Make sure output directories exist
mkdir -p $INDEX_BASE/trans1
mkdir -p $INDEX_BASE/trans3
mkdir -p $INDEX_BASE/trans5

echo "=== Building Bowtie2 index for trans1 ==="
bowtie2-build "$TRANS1" $INDEX_BASE/trans1/trans1

echo "=== Building Bowtie2 index for trans3 ==="
bowtie2-build "$TRANS3" $INDEX_BASE/trans3/trans3

echo "=== Building Bowtie2 index for trans5 ==="
bowtie2-build "$TRANS5" $INDEX_BASE/trans5/trans5

echo "=== All requested indexes built successfully ==="

### mapping ###
# Base directory for Bowtie2 indexes
INDEX_BASE=/home/jade/1_sandsmelt/rundrap/bowtie2_indexes

# Directory containing your read files
READS_DIR=/home/jade/1_sandsmelt/rundrap/out_drap

# Output base directory for SAM files and logs
MAP_BASE=/home/jade/1_sandsmelt/rundrap/mapping_results
mkdir -p "$MAP_BASE"

# Transcriptomes to map against
TRANSCRIPTOMES=("trans0" "trans1" "trans3" "trans5")

# Loop through each transcriptome
for TRANS in "${TRANSCRIPTOMES[@]}"
do
    INDEX="$INDEX_BASE/$TRANS"   # no duplicate 'trans'
    OUTDIR="$MAP_BASE/$TRANS"
    mkdir -p "$OUTDIR"

    echo "=== Mapping reads to $TRANS ==="

    # Loop through all forward read files (_1.norm.fq.gz)
    for R1 in "$READS_DIR"/*/uf*_1.norm.fq.gz
    do
        # Find the matching reverse read file
        R2=${R1/_1.norm.fq.gz/_2.norm.fq.gz}

        # Extract sample name and directory
        SAMPLE=$(basename "$R1" _1.norm.fq.gz)
        SAMPLE_DIR=$(basename "$(dirname "$R1")")

        echo "Mapping $SAMPLE_DIR ($SAMPLE) to $TRANS..."

        # Run Bowtie2 and save terminal output to a log file
        bowtie2 -x "$INDEX/$TRANS" \
            -1 "$R1" \
            -2 "$R2" \
            -q -p 22 --sensitive --no-discordant --no-mixed \
            -S "$OUTDIR/${SAMPLE_DIR}_${SAMPLE}.sam" \
            2> "$OUTDIR/${SAMPLE_DIR}_${SAMPLE}_bowtie2.txt"

        echo "Finished mapping $SAMPLE_DIR ($SAMPLE) to $TRANS"
        echo "----------------------------------------"
    done
done

echo "=== All mappings completed ==="

