#!/bin/bash
set -e

##salmon##
WORKDIR=/home/jade/1_sandsmelt/rundrap/out_drap_s2
READ1=$WORKDIR/merged_1.norm.fq.gz
READ2=$WORKDIR/merged_2.norm.fq.gz

# Transcriptomes
TX0=$WORKDIR/transcripts_fpkm_0.fa
TX05=$WORKDIR/transcripts_fpkm_0.5.fa

# Build indices
salmon index --index $WORKDIR/salmon_index_fpkm0   --transcripts $TX0
salmon index --index $WORKDIR/salmon_index_fpkm05  --transcripts $TX05

# Quantify expression
salmon quant --index $WORKDIR/salmon_index_fpkm0  --libType A \
    --dumpEq --hardFilter --skipQuant \
    -1 $READ1 -2 $READ2 \
    --output $WORKDIR/salmon_quant_fpkm0

salmon quant --index $WORKDIR/salmon_index_fpkm05 --libType A \
    --dumpEq --hardFilter --skipQuant \
    -1 $READ1 -2 $READ2 \
    --output $WORKDIR/salmon_quant_fpkm05

##corset##
# Unzip the Salmon equivalence class files
gunzip -c /home/jade/1_sandsmelt/rundrap/out_drap_s2/salmon_quant_fpkm0/aux_info/eq_classes.txt.gz \
  > /home/jade/1_sandsmelt/rundrap/out_drap_s2/salmon_quant_fpkm0/aux_info/eq_classes.txt

gunzip -c /home/jade/1_sandsmelt/rundrap/out_drap_s2/salmon_quant_fpkm05/aux_info/eq_classes.txt.gz \
  > /home/jade/1_sandsmelt/rundrap/out_drap_s2/salmon_quant_fpkm05/aux_info/eq_classes.txt

# Run Corset on each transcriptome
cd /home/jade/1_sandsmelt/rundrap/out_drap_s2

corset -i salmon_eq_classes -p corset_fpkm0  salmon_quant_fpkm0/aux_info/eq_classes.txt
corset -i salmon_eq_classes -p corset_fpkm05 salmon_quant_fpkm05/aux_info/eq_classes.txt
