#!/bin/bash

##preprocessing (trim_galore and kraken2)

#trim_galore, "--paired" is very important if following steps treat sequences in a paired-read way. 
#the last line is the file's name; the number of cores can be changed, but 10 seems to be an optimal choice based on trim_galore's instruction. 
trim_galore \
--cores 10 \
--fastqc \
--illumina \
--length 70 \
--quality 30 \
--paired \
10B_1.fastq.gz  10B_2.fastq.gz \

#kraken2
kraken2 \
--db kraken2_justin \
--threads 8 \
--unclassified-out uf10B#.fq \
--report 10B_test_report \
--confidence 0.25 \
--paired \
--gzip-compressed 10B_1_val_1.fq.gz 10B_2_val_2.fq.gz \
