#!/bin/bash

#This is used in my Docker container

##PATH
#DRAP install directory in the Docker container
cd /usr/local/src/drap

#DRAP configuration PATH
cd /usr/local/src/drap/cfg

#Edit configuration (change "local_cpu" and "n_cpu")
vi /usr/local/src/drap/cfg/drap.cfg

#Trimmed and filtered by Kraken2 sequence PATH
cd /mnt/data/pri_data/kraken

##Step 1: merge samples from brain and skin(R) separately, forward and reverse reads (1 and 2).
cd /mnt/data/pri_data/kraken && pwd && ls
# Merge all uf*B_1.fq.gz into one compressed file
cat uf*B_1.fq.gz > merged_B_1.fq.gz

# Merge all uf*B_2.fq.gz into one compressed file
cat uf*B_2.fq.gz > merged_B_2.fq.gz

# Merge all uf*R_1.fq.gz into one compressed file
cat uf*R_1.fq.gz > merged_R_1.fq.gz

# Merge all uf*R_2.fq.gz into one compressed file
cat uf*R_2.fq.gz > merged_R_2.fq.gz


##Step 2: run DRAP for denovo assembly
cd /usr/local/src/drap && pwd && ls

#Edit the CPU number used in tgicl (It always fails when more than 6 cpus are used here). This is a tool used in step 5. 
vi /usr/local/src/drap/bin/runAssembly.sh

# Change the second line into the following command
tgicl all_dbg.fa -c 6 -l 60 -p 96 -s 100000

#runDrap for brain samples
runDrap \
  --outdir /mnt/data/out_drap_s3_b \
  --R1 /mnt/data/pri_data/kraken/merged_B_1.fq.gz \
  --R2 /mnt/data/pri_data/kraken/merged_B_2.fq.gz \
  --dbg trinity \
  --no-trim \
  --norm-mem 200 \
  --dbg-mem 200 \
  --discardN \
  --coverage 0,0.5,1 \
  --no-rate \

#runDrap for skin samples
runDrap \
  --outdir /mnt/data/out_drap_s3_r \
  --R1 /mnt/data/pri_data/kraken/merged_R_1.fq.gz \
  --R2 /mnt/data/pri_data/kraken/merged_R_2.fq.gz \
  --dbg trinity \
  --no-trim \
  --norm-mem 200 \
  --dbg-mem 200 \
  --discardN \
  --coverage 0,0.5,1 \
  --no-rate \

#runMeta to merge both samples (brain and skin transcriptomes)
